# Generated by Django 5.0.3 on 2024-06-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.escritor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.ManyToManyField(blank=True, to='Libro.aniopublicacion'),
        ),
    ]
